package com.example.reviewcompanion;

public class VariableLaw {
    public static String[] Questions() {
        return new String[]{
                "The following position in a corporation are presented to you:\r\n" +
                        "\tI. President\r\n" +
                        "\tII. Treasurer\r\n" +
                        "\tIII. Corporate Secretary\r\n" +
                        "\tIV. Chairman of the Board\r\n" +
                        "Who of the foregoing must be a director of the corporation at the same time?\r\n",
                "Who may or may not be a director of a corporation?",
                "The certificate of incorporation of Rubi Corporation was issued by the Securities of Exchange Commission despite the fact that only 3 out of its 7 incorporators were residents of Philippines. Such inadvertent issuance of the certificate of incorporation:",
                "Which of the following documents may be submitted before or after incorporation?",
                "An incorporator of a stock corporation at the time of incorporation must be:",
                "A subscriber of the capital stock of a corporation still to be formed must be:",
                "The articles of incorporation of a Hegina  Computer Corporation provide for 15 directors. Which of the following is invalid concerning its by-laws?",
                "What may be the composition of the excutive committee of a corporation?",
                "The executive committee must have atleast:",
                "Which of the following causes of vacancy in the board ofdirectors may be filed by the remaining directors of they still constitute a quorum?",
                "Who may be removed as a director without cause during their term of office?",
                "Which shares may be issued with or without par value?",
                "The ryle that protects directors who act with due care and in good faith, as long as their decisions are lawful and in the best interests of the corporation.",
                "A suit brought by a stockholder in the name and on behalf of the corporation to protect corporate rights or redress wrongs committed against the corporation, whenever corporate officers refuse to bring such actions or such officers are the ones to be sued or held liable.",
                "A stock corporation, in general, is taxed in the same manner as a:",
                "Molina  is the owner of 500 shares of stock of Aberia Sales Corporation whose articles of incorporation provide  for 5 directors. In the annual election of directors, the following ran for the position of director: Asutilla, Boseo, Casiano, David, Elep, and Furio. Samorano asks you which of the following is the incorrect way of casting his votes.",
                "Which of the folowing is not a characteristic of a corporation?",
                "Which of the following provisions in the articles of incorporation cannot be ammended?",
                "No-par shares may not be issued for a price lower than:",
                "Shares that may be issued at a price higher than P5.00 per share are:",
                "Shares that may be issued at a price lower than P5.00 per share are:",
                "Other than from retained earnings, dividends may be declared out of:",
                "Which of the following is an incorrect composition of capital stock of a corporation?",
                "These statements are presented to you:\r\n" +
                        "\tI. A director is an agent of the corporation by virtue of his being elected as a director.\r\n" +
                        "\tII. A director who owns the controlling interest in a corporation has only one vote in the meeting of the board of directors.\r\n" +
                        "In your evaluation of the foregoing statements:\r\n",
                "The following vote on a per head basis, except:",
                "These statements are presented to you:\r\n" +
                        "\tI. A person may become a stockholder of a corporation through the receipt of a stock dividend given to him in payment of services previously rendered.\r\n" +
                        "\tII. A contract of subscription has for its object unissued or issued shares such as treasury shares.\r\n" +
                        "In your evaluation of the foregoing statements:\r\n",
                "The highest bidder in a delinquency sale is the one willing to pay the:",
                "Maigue is a creditor of Silvosa who is a stockholder of record of 1,000 shares of Almadrones Corporation. Silvosa sells the shares to Boseo through deed of absolute sale that has not yet been recorded in the books of Alamadrones Corporation. The transfer of the shares by Silvosa to Bacalso is:",
                "For the purpose of determining the validity of the contract entered into between the corporations with interlocking directors whose interest in one corporation is nominal and substantial in the other, the presence of the interlocking directors should not be necessary to constitute a quorum and his vote should not be necessary for the approval of the contract in the meeting of the board of directors:",
                "For the purpose of interlocking directorate, an interlocking director's interest in a corporation is considered substantial if it is:",
        };
    }
    public static String[] ChoiceA() {
        return new String[]{
                "I and II",
                "Treasurer",
                "Means Rubi Corporation is unincorporated",
                "Verification certificate as to the name of the corporation",
                "The owner of at least one share of stock of the corporation.",
                "An incorpator.",
                "That the qourum in the meetings of directors be atleast 8 directors.",
                "Directors.",
                "Three members who must act with a unanimous vote of all its members.",
                "Increase in the number of the directors.",
                "A director representing the majority stockholders.",
                "Common shares",
                "Fairness rule",
                "Individual suit.",
                "General professional partnership.",
                "500 votes each for the 6 candidates.",
                "Perpetual life.",
                "Name of corporation",
                "Stock exchange qoutation price.",
                "Par value shares",
                "Par value shares",
                "Paid-in capital in excess of par value.",
                "Both par value and par value per shares.",
                "Both statements are true.",
                "Directors of stock corporation.",
                "Both statements are true.",
                "Highest amount for the highest number of shares.",
                "Valid between Silvosa and Boseo.",
                "Of the corporation where his interest is substantial.",
                "At least 20%",
        };
    }
    public static String[] ChoiceB() {
        return new String[]{
                "III and IV",
                "Corporation Secretary",
                "Makes Rubi Corporation a de facto corporation.",
                "By-laws",
                "A member of first board of directors.",
                "A signatory to the articles of incorporation.",
                "That the qourum in the meetings of directors be at least 10 directors.",
                "Stockholders who are neither officers nor directors.",
                "Three members who must act by a majority vote of all the members.",
                "Removal of a director.",
                "A director representing the minority stickholders.",
                "Preferred shares",
                "Business judgment rule",
                "Class suit.",
                "Non-general professional partnership.",
                "500 votes each for Asutilla, Boseo, Casiano, David and Elep.",
                "Transferability of ownership interests",
                "Number and name of incorporators.",
                "Issued price.",
                "No-par value shares",
                "No-par value shares",
                "Paid-in capital in excess of issued price.",
                "Both preferred and common-shares.",
                "Both statements are false.",
                "Stockholders",
                "Both statements are false.",
                "Lowest amount for the lowest number of shares.",
                "Valid against Almadrones Corporation and Maigue.",
                "Of the corporation where his interest is merely nominal.",
                "More than 20%",
        };
    }
    public static String[] ChoiceC() {
        return new String[]{
                "I and III",
                "Both (a) and (b)",
                "Does not affect the acquisition by Rubi Corporation of the status of a de jure corporation because non-compliance of the residence requirement is a minor defect that does not affect corporate existence.",
                "Certificate of bank deposit as to the paid-up capital",
                "A duly elected officer of the corporation.",
                "A member of the incoming board of directors.",
                "That the qourum in the meetings of directors be at least 7 directors.",
                "Officers who are neither stockholders nor directors.",
                "Five members who must act with a unanimous vote of all its mmember.",
                "Expiration of the term of a director.",
                "either of (a) and (b).",
                "Both common ang preferred shares.",
                "Golden rule",
                "Representative suit.",
                "Sole-proprietorship.",
                "2,500 votes for Asutilla.",
                "Unlimited liability on the part of the stockholders",
                "Term of existence",
                "Market price",
                "Both (a) and (b)",
                "Both (a) and (b)",
                "Both (a) and (b).",
                "Either par value or no-par value shares.",
                "Statement I is true; statement II is false.",
                "Trustees of non-stock corporation.",
                "Only statement I is true",
                "Full amount of the balance of the subscription, accrued interest, cost of advertisement and expenses of sale for the smallest number of shares.",
                "Valid as to Silvosa, Boseo, Montero Corporation and Maigue.",
                "Of both corporations.",
                "At least 25%",

        };
    }
    public static String[] ChoiceD() {
        return new String[]{
                "I and II",
                "Neither (a) nor (b)",
                "Results in the automatic dissolution of the Rubi Corporation upon discovery by SEC of the corporation's failure to comply with the residence requirement for incorporators.",
                "Articles of iincorporation.",
                "All of the foregoing.",
                "None of the foregoing.",
                "The by-laws do not mention anything about the quorum in the meetings of directors.",
                "A combination of (a),(b) and (c).",
                "Five memebers who must act by a majority vote of all its memembers.",
                "Disqualification of a director.",
                "Neither of (a) and (b) because they can only be replaced upon the expiration of their term of office through the election of another in their place since the removal is without cause.",
                "Neither common nor preferreed shares.",
                "Anti-trust rule",
                "Derivative suit.",
                "Cooperative.",
                "1,000 votes for Asutilla, 1,000 votes for Boseo, and 500 votes for Casiano.",
                "Ability to attract large amount of capital.",
                "Primary purpose",
                "Fair market value.",
                "Neither (a) and (b)",
                "Neither (a) nor (b)",
                "Neither (a) nor (b)",
                "Either common or preferred shares.",
                "Statement I is false; statement II is true.",
                "Members (of a non-stock corporation.)",
                "Only statement II is true.",
                "Full amount of the balance of the subscription, accrued interest, cost of advertisement and expenses of sale for the highest number of shares.",
                "Not valid as regards any of those mentioned in (c) until it has been recorded in the books of Almadrones Corporation.",
                "Of neither corporation for as long as there is no fraud and the contract is fair and reasonable under the circumstances because he has a personality seperate and distinct from both corporations.",
                "More than 25%",

        };
    }
    public static String[] Answers() {
        return new String[]{
                "I and II",
                "Both (a) and (b)",
                "Makes Rubi Corporation a de facto corporation.",
                "By-laws",
                "The owner of at least one share of stock of the corporation.",
                "None of the foregoing.",
                "That the qourum in the meetings of directors be at least 7 directors.",
                "Directors.",
                "Three members who must act by a majority vote of all the members.",
                "Disqualification of a director.",
                "A director representing the majority stockholders.",
                "Common shares",
                "Business judgment rule",
                "Derivative suit.",
                "Non-general professional partnership.",
                "500 votes each for the 6 candidates.",
                "Unlimited liability on the part of the stockholders",
                "Number and name of incorporators.",
                "Issued price.",
                "Both (a) and (b)",
                "Par value shares",
                "Paid-in capital in excess of par value.",
                "Either common or preferred shares.",
                "Statement I is false; statement II is true.",
                "Stockholders",
                "Only statement II is true.",
                "Full amount of the balance of the subscription, accrued interest, cost of advertisement and expenses of sale for the smallest number of shares.",
                "Valid between Silvosa and Boseo.",
                "Of the corporation where his interest is merely nominal.",
                "More than 20%",
        };
    }
}